[versions]
kotlin = "2.3.0-RC"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.10.0-RC"
minestom = "2025.12.20c-1.21.11"
hytale = "2026.01.24-6e2d4fc36"
korlibs = "6.0.0"
nats = "2.24.1"
kotlinxCoroutines = "1.10.2"
shadow = "9.3.0"
colormath = "3.6.1"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }

minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
hytale = { module = "com.hypixel.hytale:Server", version.ref = "hytale" }

korlibs-math = { module = "com.soywiz:korlibs-math", version.ref = "korlibs" }
korlibs-math-core = { module = "com.soywiz:korlibs-math-core", version.ref = "korlibs" }
korlibs-math-vector = { module = "com.soywiz:korlibs-math-vector", version.ref = "korlibs" }

nats = { module = "io.nats:jnats", version.ref = "nats" }

kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

colormath = { module = "com.github.ajalt.colormath:colormath", version.ref = "colormath" }

[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }